[versions]
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.4"

navigation3 = "1.0.0"
composeBom = "2026.01.00"
androidxHiltNavigation = "1.3.0"

spotless = "7.2.1"
moshi = "1.15.2"
daggerHilt = "2.59"
arrow = "2.1.2"
kotlintest = "2.0.0"
kotest = "6.0.4"
kotlinSerialization = "2.1.21"

[libraries]
# Navigation 3
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigation" }

# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHilt" }

# moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

# arrow
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }

# kotest
kotlintest = { group = "io.kotlintest", name = "kotlintest" , version.ref = "kotlintest"}
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5" , version.ref = "kotest"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotest = { id = "io.kotest", version.ref = "kotest" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }

